from prometheus_client import Counter, Histogram, Gauge

# ─────────────────────────────────────────────
# Ingestion & Analysis
# ─────────────────────────────────────────────

articles_ingested = Counter(
    "articles_ingested_total",
    "Total articles ingested from all sources",
    ["source"]
)

articles_analyzed = Counter(
    "articles_analyzed_total",
    "Articles processed through the AI analysis pipeline",
    ["status"]  # "success" | "failed"
)

analysis_latency = Histogram(
    "article_analysis_seconds",
    "End-to-end AI analysis pipeline latency per article",
    buckets=[0.5, 1, 2, 5, 10, 30]
)

# ─────────────────────────────────────────────
# Groq API
# ─────────────────────────────────────────────

groq_tokens = Counter(
    "groq_tokens_total",
    "Total tokens consumed via Groq API",
    ["model", "task"]
)

groq_latency = Histogram(
    "groq_call_seconds",
    "Groq API call round-trip latency",
    buckets=[0.1, 0.5, 1, 2, 5]
)

# ─────────────────────────────────────────────
# Embeddings (Ollama)
# ─────────────────────────────────────────────

embedding_latency = Histogram(
    "embedding_seconds",
    "Ollama nomic-embed-text embedding latency per document",
    buckets=[0.05, 0.1, 0.25, 0.5, 1, 2]
)

# ─────────────────────────────────────────────
# pgvector / RAG
# ─────────────────────────────────────────────

vector_search_latency = Histogram(
    "vector_search_seconds",
    "pgvector ANN search latency (HNSW index)",
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1]
)

rag_queries = Counter(
    "rag_queries_total",
    "Total RAG analyst queries executed"
)

# ─────────────────────────────────────────────
# AI Platform Events
# ─────────────────────────────────────────────

events_detected = Counter(
    "events_detected_total",
    "Geopolitical events auto-detected via HDBSCAN clustering"
)

entities_extracted = Counter(
    "entities_extracted_total",
    "Named entities extracted and upserted into knowledge graph",
    ["entity_type"]
)

forecasts_generated = Counter(
    "forecasts_generated_total",
    "Intelligence forecasts generated by the forecasting engine"
)

# ─────────────────────────────────────────────
# Infrastructure
# ─────────────────────────────────────────────

# Gauge for showing current queue depth — set by an optional scheduler task
celery_queue_depth = Gauge(
    "celery_queue_depth",
    "Number of pending tasks in the Celery queue",
    ["queue"]
)
